window.alert('Minha primeira mensagem'); // Vai criar um alerta...
window.confirm('Está gostando de JS?'); // Janela com botão Ok e Cancelar...
window.prompt('Qual é seu nome?'); // Vai perguntar nome...